# Generated by Django 5.1.2 on 2024-10-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
